#cmd or bat easy to run. single click job done.
PowerShell Set-ExecutionPolicy Unrestricted -f
#PowerShell . { iwr -useb http://boxstarter.org/bootstrapper.ps1 };
#list of chocolatey packages will be installed
cinst -y 010editor.flare
cinst -y 7zip.flare
cinst -y AD-control-paths.fireeye
cinst -y ADACLScanner.fireeye
cinst -y ADAPE-Script.fireeye
cinst -y ADExplorer.fireeye
cinst -y adobereader.fireeye
cinst -y ADOffline.fireeye
cinst -y ADRecon.fireeye
cinst -y amass.docker.fireeye
cinst -y apimonitor.fireeye
cinst -y apimonitor.flare
cinst -y apktool.flare
cinst -y Autopsy.fireeye
cinst -y ASREPRoast.fireeye
cinst -y autoit.fireeye
cinst -y beroot.fireeye
cinst -y binaryninja.flare
cinst -y BloodHound.fireeye
cinst -y BloodHound-Custom-Queries.fireeye
cinst -y burp.free.fireeye
cinst -y burp.free.flare
cinst -y bytecode-viewer.flare
cinst -y bytehist.fireeye
cinst -y CheckPlease.fireeye
cinst -y citrix-receiver.fireeye
cinst -y cmder.fireeye
cinst -y cmdermini.flare
cinst -y common.fireeye
cinst -y contextmenu.fireeye
cinst -y Covenant.fireeye
cinst -y CrackMapExec.fireeye
cinst -y CrackMapExecWin.fireeye
cinst -y CredNinja.fireeye
cinst -y cutter.flare
cinst -y cyberchef.flare
cinst -y cygwin.flare
cinst -y DAMP.fireeye
cinst -y de4dot.flare
cinst -y DefenderCheck.fireeye
cinst -y demiguise.fireeye
cinst -y dex2jar.flare
cinst -y die.flare
cinst -y dnsd.flare
cinst -y dnspy.flare
cinst -y dnsrecon.fireeye
cinst -y docker.fireeye
cinst -y DomainPasswordSpray.fireeye
cinst -y DotNetToJScript.fireeye
cinst -y dotPeek.flare
cinst -y DSInternals.fireeye
cinst -y Dumpert.fireeye
cinst -y Egress-Assess.fireeye
cinst -y Elite.fireeye
cinst -y EvilClippy.fireeye
cinst -y Exchange-AD-Privesc.fireeye
cinst -y exe2aut.fireeye
cinst -y exeinfope.flare
cinst -y explorersuite.flare
cinst -y fakenet-ng.python.fireeye
cinst -y fakenet-ng.python.flare
cinst -y farmanager.flare
cinst -y ffdec.flare
cinst -y fiddler.fireeye
cinst -y fileinsight.flare
cinst -y firefox.fireeye
cinst -y flare-floss.fireeye
cinst -y flare-qdb.python.flare
cinst -y floss.python.flare
cinst -y FOCA.fireeye
cinst -y fuzzdb.fireeye
cinst -y GadgettoJScript.fireeye
cinst -y Generate-Macro.fireeye
cinst -y Get-LAPSPasswords.fireeye
cinst -y Get-ReconInfo.fireeye
cinst -y ghidra.fireeye
cinst -y gimp.fireeye
cinst -y github
cinst -y GoBuster.fireeye
cinst -y GoFetch.fireeye
cinst -y googlechrome.fireeye
cinst -y googlechrome.flare
cinst -y gowitness.fireeye
cinst -y Greenshot.fireeye
cinst -y Grouper2.fireeye
cinst -y hashcalc.flare
cinst -y hashcat.fireeye
cinst -y hashmyfiles.flare
cinst -y heidisql.fireeye
cinst -y hexchat.fireeye
cinst -y hfs.fireeye
cinst -y hollowshunter.fireeye
cinst -y HTTrack.fireeye
cinst -y hxd.fireeye
cinst -y hxd.flare
cinst -y hyperv.fireeye
cinst -y idafree.flare
cinst -y idafree70.flare
cinst -y idr.small.flare
cinst -y ilspy.flare
cinst -y impacket-examples-windows.fireeye
cinst -y impacket.fireeye
cinst -y ImpRec.fireeye
cinst -y innoextract.fireeye
cinst -y innounp.fireeye
cinst -y Internal-Monologue.fireeye
cinst -y Inveigh.fireeye
cinst -y Invoke-ACLPwn.fireeye
cinst -y Invoke-CradleCrafter.fireeye
cinst -y Invoke-CredentialPhisher.fireeye
cinst -y Invoke-DCOM.fireeye
cinst -y Invoke-DOSfuscation.fireeye
cinst -y Invoke-Obfuscation.fireeye
cinst -y Invoke-Phant0m.fireeye
cinst -y Invoke-PowerThIEf.fireeye
cinst -y Invoke-PSImage.fireeye
cinst -y Invoke-TheHash.fireeye
cinst -y java-deobfuscator-gui.fireeye
cinst -y jd-gui.flare
cinst -y juicy-potato.fireeye
cinst -y kali.fireeye --timeout 7200
cinst -y kali-lite.fireeye --timeout 7200
cinst -y kali_windowsbinaries.fireeye
cinst -y KeeFarce.fireeye
cinst -y keepass.fireeye
cinst -y KeeThief.fireeye
cinst -y kmdloader.flare
cinst -y LAPSToolkit.fireeye
cinst -y lessmsi.fireeye
cinst -y libraries.go.fireeye
cinst -y libraries.python2.fireeye
cinst -y libraries.python2.flare
cinst -y libraries.python3.fireeye
cinst -y libraries.python3.flare
cinst -y lonelypotato.fireeye
cinst -y lordpe.flare
cinst -y luckystrike.fireeye
cinst -y MailSniper.fireeye
cinst -y malware-jail.fireeye
cinst -y MAP.flare
cinst -y metasploit.flare
cinst -y metatwin.fireeye
cinst -y Mimikatz.fireeye
cinst -y mimikittenz.fireeye
cinst -y mobaxterm.fireeye
cinst -y msoffcrypto-crack.fireeye
cinst -y nasm.fireeye
cinst -y ncat.flare
cinst -y neo4j-community.fireeye
cinst -y Net-GPPPassword.fireeye
cinst -y NetRipper.fireeye
cinst -y NetshHelperBeacon.fireeye
cinst -y nirlauncher.fireeye
cinst -y nishang.fireeye
cinst -y nmap.fireeye
cinst -y nmap.flare
cinst -y notepadplusplus-textfx.fireeye
cinst -y notepadplusplus.flare
cinst -y nps.fireeye
cinst -y NtdsAudit.fireeye
cinst -y OffensiveCSharp.fireeye
cinst -y officemalscanner.flare
cinst -y offvis.flare
cinst -y oledump.fireeye
cinst -y oletools.fireeye
cinst -y ollydbg.flare
cinst -y ollydbg.ollydump.flare
cinst -y ollydbg.ollydumpex.flare
cinst -y ollydbg2.flare
cinst -y ollydbg2.ollydumpex.flare
cinst -y OpenSSL.flare
cinst -y openvpn.fireeye
cinst -y orca.fireeye
cinst -y pafishmacro.fireeye
cinst -y PayloadsAllTheThings.fireeye
cinst -y pdfid.flare
cinst -y pdfparser.flare
cinst -y PdfStreamDumper.flare
cinst -y pebear.flare
cinst -y peid.flare
cinst -y pesieve.fireeye
cinst -y pestudio.flare
cinst -y peview.flare
cinst -y pidgin.fireeye
cinst -y pmalabs.flare
cinst -y powercat.fireeye
cinst -y PowerLessShell.fireeye
cinst -y PowerLurk.fireeye
cinst -y PowerPriv.fireeye
cinst -y PowerShdll.fireeye
cinst -y PowerShell-Suite.fireeye
cinst -y PowerSploit.fireeye
cinst -y PowerUpSQL.fireeye
cinst -y PowerView.fireeye
cinst -y ppee.fireeye
cinst -y Privesc.fireeye
cinst -y PrivExchange.fireeye
cinst -y Probable-Wordlists.fireeye
cinst -y procdot.fireeye
cinst -y processdump.fireeye
cinst -y processhacker.flare
choco install procmon
cinst -y proxycap.fireeye
cinst -y PSAmsi.fireeye
cinst -y PSAttack.fireeye
cinst -y PSBits.fireeye
cinst -y PSDecode.fireeye
cinst -y PSReflect.fireeye
cinst -y putty.fireeye
cinst -y PwnedPasswordsNTLM.fireeye
cinst -y py2exedecompiler.flare
cinst -y pyinstxtractor.fireeye
cinst -y python2.x86.nopath.flare
cinst -y radare2.flare
cinst -y Recon-AD.fireeye
cinst -y RedTeamPowershellScripts.fireeye
cinst -y regshot.flare
cinst -y resourcehacker.flare
cinst -y RetDec.flare
cinst -y RiskySPN.fireeye
cinst -y RobotsDisallowed.fireeye
cinst -y RottenPotatoNG.fireeye
cinst -y rsat.fireeye
choco install rsat
cinst -y rtfdump.fireeye
cinst -y Rubeus.fireeye
cinst -y ruler.fireeye
cinst -y rundotnetdll.flare
cinst -y SafetyKatz.fireeye
cinst -y scdbg.flare
cinst -y ScreenToGif.fireeye
cinst -y Seatbelt.fireeye
cinst -y SecLists.fireeye
cinst -y SessionGopher.fireeye
cinst -y ShareAudit.fireeye
cinst -y Sharp-Suite.fireeye
cinst -y SharpClipHistory.fireeye
cinst -y SharpDPAPI.fireeye
cinst -y SharpDump.fireeye
cinst -y SharpExchangePriv.fireeye
cinst -y SharpExec.fireeye
cinst -y SharpHound.fireeye
cinst -y SharpRoast.fireeye
cinst -y SharpSploit.fireeye
cinst -y SharpUp.fireeye
cinst -y SharpView.fireeye
cinst -y SharpWMI.fireeye
cinst -y ShareAudit.fireeye
cinst -y shellcode_launcher.flare
cinst -y SilkETW.fireeye
cinst -y simplednscrypt.fireeye
cinst -y spiderfoot.docker.fireeye
cinst -y SpoolerScanner.fireeye
cinst -y SpoolSample.fireeye
cinst -y spystudio.flare
cinst -y sqlitebrowser.fireeye
cinst -y sqlserver-cmdlineutils.fireeye
cinst -y StarFighters.fireeye
cinst -y subdomain-bruteforce.fireeye
cinst -y SublimeText3.fireeye
cinst -y SysAnalyzer.flare
cinst -y sysinternals.fireeye
choco install sysinternals
cinst -y SysWhispers.fireeye
cinst -y telnet.fireeye
cinst -y ThreadContinue.fireeye
cinst -y thunderbird.fireeye
cinst -y TikiTorch.fireeye
cinst -y tor-browser.fireeye
cinst -y TrustVisualizer.fireeye
cinst -y UACME.fireeye
cinst -y uniextract2.fireeye
cinst -y vbdecompiler.flare
cinst -y vcbuildtools.fireeye
cinst -y vcredist-all.flare
cinst virustotaluploader.fireeye
cinst -y vim.flare
cinst -y vlc.fireeye
cinst -y vmware-horizon-client.fireeye
cinst -y vmwarevsphereclient.fireeye
cinst -y vnc-viewer.fireeye
cinst -y volatility.flare
cinst -y vscode.fireeye
cinst -y vssown.fireeye
cinst -y vulcan.fireeye
cinst -y Watson.fireeye
cinst -y wfuzz.fireeye
cinst -y windbg.fireeye
cinst -y windbg.flare
cinst -y windbg.kenstheme.flare
cinst -y windbg.ollydumpex.flare
cinst -y windbg.pykd.flare
cinst -y windump.fireeye
cinst -y winscp.fireeye
cinst -y wireshark.fireeye
cinst -y wireshark.flare
cinst -y WMImplant.fireeye
cinst -y WMIOps.fireeye
cinst -y wsl.fireeye
cinst -y x64dbg.fireeye
cinst -y x64dbg.flare
cinst -y x64dbg.ollydumpex.fireeye
cinst -y x64dbg.py.flare
cinst -y xorsearch.flare
cinst -y xorstrings.flare
cinst -y yara.flare
cinst -y yed.fireeye
cinst -y zap.fireeye
cinst -y zBang.fireeye
#to update all of the packages
cup all
